// frontend/components/displays/DisplaysCanvas.tsx
import { useAtom } from "jotai"
import { useEffect, useRef, useState } from "react"

import { FenceApi } from "@/lib/api"
import { displayStateAtom, regionStateAtom } from "@/lib/store"

export const DisplaysCanvas: React.FC = () => {
  const canvas = useRef(null)

  const [displays, setDisplays] = useAtom(displayStateAtom)
  const [regions, setRegions] = useAtom(regionStateAtom)

  const [topOffset, setTopOffset] = useState(0)
  const [leftOffset, setLeftOffset] = useState(0)
  const [factor, setFactor] = useState(0.1)
  const [canvasWidth, setCavasWidth] = useState(0)
  const [canvasHeight, setCanvasHeight] = useState(0)

  const drawCanvas = () => {
    setTopOffset(-displays.reduce((acc, display) => Math.min(acc, display.top), 0))
    setLeftOffset(-displays.reduce((acc, display) => Math.min(acc, display.left), 0))
    const highestRight = displays.reduce(
      (acc, display) => Math.max(acc, display.left + leftOffset + display.width),
      0,
    )
    const highestBottom = displays.reduce(
      (acc, display) => Math.max(acc, display.top + topOffset + display.height),
      0,
    )

    setCavasWidth(highestRight * factor)
    setCanvasHeight(highestBottom * factor)
  }
  useEffect(() => {
    drawCanvas()

    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [displays])

  return (
    <div className="bg-gray-300 p-4 dark:bg-gray-950">
      <div>
        <div
          className="relative"
          ref={canvas}
          style={{ width: `${canvasWidth}px`, height: `${canvasHeight}px` }}
        >
          {/* {#each $displays as display}
				<div
					className="bg-gray-400 dark:bg-gray-800 border border-gray-600 dark:border-gray-700"
					style="
					position: absolute;
					top: {display.top * factor + topOffset * factor}px;
					left: {display.left * factor + leftOffset * factor}px;
					width: {display.width * factor}px;
					height: {display.height * factor}px;"
				/>
			{/each}

			{#each $regions as region}
				<div
					className="absolute bg-red-400/10"
					style="
					top: {region.y * factor + topOffset * factor}px;
					left: {region.x * factor + leftOffset * factor}px;
					width: {region.width * factor}px;
					height: {region.height * factor}px;"
				/>
			{/each} */}
          {displays.map((display, idx) => (
            <div
              key={idx}
              className="absolute border border-gray-600 bg-gray-400 dark:border-gray-700 dark:bg-gray-800"
              style={{
                top: `${display.top * factor + topOffset * factor}px`,
                left: `${display.left * factor + leftOffset * factor}px`,
                width: `${display.width * factor}px`,
                height: `${display.height * factor}px`,
              }}
            />
          ))}

          <div
            className="absolute h-2 w-2 rounded-full bg-violet-800"
            // style="top: {cursorY * factor + topOffset * factor}px; left: {cursorX * factor +
            // 		leftOffset * factor}px"
          />
        </div>
      </div>

      <div className="mt-4 flex items-center justify-end space-x-4 text-xs font-semibold text-gray-700 dark:text-gray-400">
        <div className="flex items-center">
          <input
            // bind:checked={showScreenshots}
            // on:change={handleShowScreenshots}
            type="checkbox"
            name="showScreenshots"
            id="checkbox-show-screenshots"
          />
          <label htmlFor="checkbox-show-screenshots" className="ml-2">
            {" "}
            Show Screenshots{" "}
          </label>
        </div>
        <button
          //   onClick={() => void FenceApi.refreshDisplays()}
          className="flex items-center space-x-2 rounded bg-gray-400/60 px-5 py-1 transition-all hover:bg-gray-400/80 dark:bg-gray-800 dark:hover:bg-gray-700"
        >
          {/* <Fa icon={faRefresh} /> */}
          <p>Refresh</p>
        </button>
      </div>
    </div>
  )
}

// frontend/src/components/displays/DisplaysCanvas.svelte
<script lang="ts">
	import type { FenceClientStore } from '$lib/store';
	import { getContext, onDestroy } from 'svelte';
	import { onMount } from 'svelte';
	import { faRefresh } from '@fortawesome/free-solid-svg-icons';
	import Fa from 'svelte-fa';
	import { listen } from '@tauri-apps/api/event';
	import type { IDisplayScreenshot } from '$lib/types/displays';
	import { invoke } from '@tauri-apps/api';

	const context: FenceClientStore = getContext('fenceClientStore');
	const { displays, regions, screenshots } = context;
	let canvas: HTMLDivElement;
	let factor = 0.1;
	let topOffset = 0;
	let leftOffset = 0;
	let cursorX = 0;
	let cursorY = 0;
	let unlisten: () => void;
	let showScreenshots = false; //TODO This should be stored in the local config

	interface ICursorPositionPayload {
		x: number;
		y: number;
	}

	const drawCanvas = () => {
		topOffset = -$displays.reduce((acc, display) => Math.min(acc, display.top), 0);
		leftOffset = -$displays.reduce((acc, display) => Math.min(acc, display.left), 0);

		const highestRight = $displays.reduce(
			(acc, display) => Math.max(acc, display.left + leftOffset + display.width),
			0
		);
		const highestBottom = $displays.reduce(
			(acc, display) => Math.max(acc, display.top + topOffset + display.height),
			0
		);

		canvas.style.width = `${highestRight * factor}px`;
		canvas.style.height = `${highestBottom * factor}px`;
	};

	const handleShowScreenshots = () => {
		if (showScreenshots) {
			invoke<IDisplayScreenshot[]>('get_display_screenshots').then((result) => {
				console.log(result);
				console.log($displays);
				$screenshots = result;
			});
		} else {
			$screenshots = [];
		}
	};

	onMount(async () => {
		drawCanvas();

		displays.subscribe(() => {
			drawCanvas();
		});

		unlisten = await listen<ICursorPositionPayload>('EVENT_CURSOR_POSITION', (event) => {
			cursorX = event.payload.x;
			cursorY = event.payload.y;
		});
	});

	onDestroy(() => {
		unlisten();
	});
</script>

<div class="p-4 bg-gray-300 dark:bg-gray-950">
	<div>
		<div class="relative" bind:this={canvas}>
			{#each $displays as display}
				<div
					class="bg-gray-400 dark:bg-gray-800 border border-gray-600 dark:border-gray-700"
					style="
					position: absolute;
					top: {display.top * factor + topOffset * factor}px;
					left: {display.left * factor + leftOffset * factor}px;
					width: {display.width * factor}px;
					height: {display.height * factor}px;"
				/>
			{/each}

			{#each $regions as region}
				<div
					class="absolute bg-red-400/10"
					style="
					top: {region.y * factor + topOffset * factor}px;
					left: {region.x * factor + leftOffset * factor}px;
					width: {region.width * factor}px;
					height: {region.height * factor}px;"
				/>
			{/each}

			<div
				class="w-2 h-2 bg-violet-800 rounded-full absolute"
				style="top: {cursorY * factor + topOffset * factor}px; left: {cursorX * factor +
					leftOffset * factor}px"
			/>
		</div>
	</div>

	<div
		class="flex items-center justify-end mt-4 space-x-4 text-xs font-semibold text-gray-700 dark:text-gray-400"
	>
		<div class="flex items-center">
			<input
				bind:checked={showScreenshots}
				on:change={handleShowScreenshots}
				type="checkbox"
				name="showScreenshots"
				id="checkbox-show-screenshots"
			/>
			<label for="checkbox-show-screenshots" class="ml-2"> Show Screenshots </label>
		</div>
		<button
			on:click={async () => await context.refreshDisplays()}
			class="flex items-center space-x-2 py-1 px-5 bg-gray-400/60 dark:bg-gray-800 rounded transition-all hover:bg-gray-400/80 dark:hover:bg-gray-700"
		>
			<Fa icon={faRefresh} />
			<p>Refresh</p>
		</button>
	</div>
</div>
