// frontend/pages/hostname/[hostname].tsx
import { ConnectionStatusBar } from "@/components/connection/ConnectionStatusBar"
import { DisplaysCanvas } from "@/components/displays/DisplaysCanvas"

export default function Hostname() {
  return (
    <div className="grid h-screen grid-flow-row grid-rows-[1fr_auto]">
      <div className="mx-auto">
        <DisplaysCanvas />
      </div>
      <ConnectionStatusBar />
    </div>
  )
}

// frontend/pages/hostname/[hostname].vue
<script lang="ts">
import { defineComponent } from "vue"
const route = useRoute()

export default defineComponent({
  setup() {
    console.log(route)
  },
  data() {
    return {
      hostname: route.params.hostname,
    }
  },
})
</script>

<template>
  <div
    class="w-screen h-screen overflow-hidden grid grid-flow-row grid-rows-[1fr_auto]"
  >
    <div class="mx-auto"></div>
    <ConnectionStatusBar />
  </div>
</template>
