// frontend/components/connection/ConnectionStatusBar.tsx
import {
  faCircleNotch,
  faPlug,
  faPlugCircleXmark,
} from "@fortawesome/free-solid-svg-icons"
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome"
import clsx from "clsx"
import { useAtomValue } from "jotai"

import { FenceApi } from "@/lib/api"
import { fenceStateAtom } from "@/lib/store"
import { GrpcStatus } from "@/lib/types/grpc-status"

export const ConnectionStatusBar: React.FC = () => {
  const state = useAtomValue(fenceStateAtom)

  const statusButtonClick = () => {
    if (
      [GrpcStatus.CONNECTION_LOST, GrpcStatus.DISCONNECTED, GrpcStatus.ERROR].includes(
        state.grpcStatus,
      ) &&
      state.currentHostname
    ) {
      void FenceApi.connectGrpc(state.currentHostname)
    }
  }

  return (
    <div className="flex h-6 w-full items-center bg-gray-300 text-sm dark:bg-gray-800">
      <button
        onClick={statusButtonClick}
        className={clsx(
          "flex h-6 items-center space-x-2 px-4 transition-all",
          state.grpcStatus === GrpcStatus.CONNECTED &&
            "bg-green-400/50 text-green-900 dark:bg-green-400/20 dark:text-green-400",
          state.grpcStatus === GrpcStatus.CONNECTING &&
            "bg-yellow-400/50 text-yellow-900 dark:bg-yellow-400/20 dark:text-yellow-400",
          (state.grpcStatus === GrpcStatus.DISCONNECTED ||
            state.grpcStatus === GrpcStatus.CONNECTION_LOST ||
            state.grpcStatus === GrpcStatus.ERROR) &&
            "bg-red-400/50 text-red-900 dark:bg-red-400/20 dark:text-red-400",
        )}
      >
        <div className="flex w-6 items-center">
          {state.grpcStatus === GrpcStatus.CONNECTED && (
            <FontAwesomeIcon icon={faPlug} />
          )}
          {state.grpcStatus === GrpcStatus.CONNECTING && (
            <FontAwesomeIcon
              icon={faCircleNotch}
              className="m-0 h-4 origin-center animate-spin p-0"
            />
          )}
          {[
            GrpcStatus.CONNECTION_LOST,
            GrpcStatus.DISCONNECTED,
            GrpcStatus.ERROR,
          ].includes(state.grpcStatus) && (
            <FontAwesomeIcon icon={faPlugCircleXmark} className="animate-pulse" />
          )}
        </div>
        <span>{state.currentHostname}</span>
      </button>
    </div>
  )
}

// frontend/components/connection/ConnectionStatusBar.vue
<script lang="ts">
import { defineComponent } from "vue"
import { FenceApi } from "~/lib/api"
import { IFenceState } from "~/lib/types/fence-state"
import { GrpcStatus } from "~/lib/types/grpc-status"

export default defineComponent({
  setup() {
    const state = inject<Ref<IFenceState | undefined>>("state")

    const handleButtonClick = () => {
      if (state?.value) {
        if (
          [
            GrpcStatus.CONNECTION_LOST,
            GrpcStatus.DISCONNECTED,
            GrpcStatus.ERROR,
          ].includes(state?.value?.grpcStatus)
        ) {
          if (state?.value?.currentHostname) {
            FenceApi.connectGrpc(state?.value?.currentHostname)
          }
        }
      }
    }

    return {
      handleButtonClick,
      state,
      GrpcStatus,
    }
  },
})
</script>

<template>
  <div class="flex h-6 w-full items-center text-sm bg-white-rock-200">
    <button
      @click="handleButtonClick"
      :class="{
        'flex h-6 items-center space-x-2 px-4 transition-all': true,
        'bg-twilight-blue-600': state?.grpcStatus === GrpcStatus.CONNECTED,
        'bg-mako-700':
          state?.grpcStatus === GrpcStatus.DISCONNECTED ||
          state?.grpcStatus === GrpcStatus.ERROR ||
          state?.grpcStatus === GrpcStatus.CONNECTION_LOST,
        'bg-tango-500': state?.grpcStatus === GrpcStatus.CONNECTING,
      }"
    >
      <div class="flex w-6 items-center">
        <font-awesome-icon
          v-if="state?.grpcStatus === GrpcStatus.CONNECTED"
          icon="fa-plug"
        />
        <font-awesome-icon
          v-if="state?.grpcStatus === GrpcStatus.CONNECTING"
          icon="fa-circle-notch"
          class="animate-spin"
        />
        <font-awesome-icon
          v-if="
            [
              GrpcStatus.CONNECTION_LOST,
              GrpcStatus.DISCONNECTED,
              GrpcStatus.ERROR,
            ].includes(state?.grpcStatus)
          "
          icon="fa-plug-circle-xmark"
        />
      </div>
      <p>{{ state?.currentHostname }}</p>
    </button>
  </div>
</template>
